Import(["env", "libDBGp"])

libDBGpTest = env.StaticLibrary(target="libDBGpTest", source=[
		"Connection.cpp",
		"Server.cpp"
	]
)
env.Alias("test", libDBGpTest)

Return("libDBGpTest")

# vim:set ts=8 sw=8 noet nocin ai ft=python:
