import glob
import os
import platform

Import(["env"])

if os.name == "nt":
	actions = []
	files = []
	for file in glob.glob("*.png"):
		actions.append(env.Data("%s.data.c" % file, file))
	images = env.StaticLibrary(target="images", source=["images.cpp"])
	env.Depends(images, actions)
elif platform.system() == "Darwin":
	images = None
else:
	Import(["prefix"])
	install = env.Install("%s/share/dubnium" % prefix, glob.glob("*.png"))
	images = env.Alias("install", install)

Return("images")

# vim:set ts=8 sw=8 noet nocin ai ft=python:
