import glob

Import(["env"])

actions = []
files = []
for file in glob.glob("*.png"):
	actions.append(env.Data("%s.data.c" % file, file))
images = env.StaticLibrary(target="images", source=["images.cpp"])
env.Depends(images, actions)

Return("images")
