import os

Import(["env", "libDBGp"])

source = [
	"ArtProvider.cpp",
	"BreakpointPanel.cpp",
	"ConnectionPage.cpp",
	"DebugPage.cpp",
	"FunctionBreakpointDialog.cpp",
	"Location.cpp",
	"MainFrame.cpp",
	"OutputPanel.cpp",
	"PaneMenu.cpp",
	"PrefDialog.cpp",
	"PropertiesPanel.cpp",
	"PropertyDialog.cpp",
	"PropertyTreeItem.cpp",
	"SourcePanel.cpp",
	"SourceTextCtrl.cpp",
	"StackLevelClientData.cpp",
	"StackPanel.cpp",
	"ToolbarPanel.cpp",
	"ToolTipWindow.cpp",
	"WelcomePage.cpp",
	"Dubnium.cpp",
	libDBGp
]

if os.name == "nt":
	rc = env.RES("Dubnium.rc")
	source.append(rc)

prog = env.Program(
	target="Dubnium",
	source=source
)

env.Default(prog)
env.Clean(prog, [
		"Dubnium.exe.manifest",
		"Dubnium.ilk",
		"Dubnium.pdb"
	]
)

if os.name != "nt":
	Import(["prefix"])
	install = env.InstallAs("%s/bin/dubnium" % prefix, prog)
	env.Alias("install", install)

Return("prog")

# vim:set ts=8 sw=8 noet nocin ai ft=python:
