Import(["env", "libDBGp"])

prog = env.Program(target="SocketServerTest", source=["SocketServerTest.cpp", libDBGp])
env.Alias("SocketServerTest", prog)
env.Clean(prog, [
		"SocketServerTest.exe.manifest",
		"SocketServerTest.ilk",
		"SocketServerTest.pdb"
		])

# vim:set ts=8 sw=8 noet nocin ai ft=python:
